/**
 * @fileoverview gRPC-Web generated client stub for pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.1
// source: guide.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var empty_pb = require('./empty_pb.js')
const proto = {};
proto.pb = require('./guide_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pb.GuideServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pb.GuideServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.CreateGuideRequest,
 *   !proto.pb.Guide>}
 */
const methodDescriptor_GuideService_Create = new grpc.web.MethodDescriptor(
  '/pb.GuideService/Create',
  grpc.web.MethodType.UNARY,
  proto.pb.CreateGuideRequest,
  proto.pb.Guide,
  /**
   * @param {!proto.pb.CreateGuideRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.Guide.deserializeBinary
);


/**
 * @param {!proto.pb.CreateGuideRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.Guide)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.Guide>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.GuideServiceClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.GuideService/Create',
      request,
      metadata || {},
      methodDescriptor_GuideService_Create,
      callback);
};


/**
 * @param {!proto.pb.CreateGuideRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.Guide>}
 *     Promise that resolves to the response
 */
proto.pb.GuideServicePromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.GuideService/Create',
      request,
      metadata || {},
      methodDescriptor_GuideService_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.GetGuideRequest,
 *   !proto.pb.Guide>}
 */
const methodDescriptor_GuideService_Get = new grpc.web.MethodDescriptor(
  '/pb.GuideService/Get',
  grpc.web.MethodType.UNARY,
  proto.pb.GetGuideRequest,
  proto.pb.Guide,
  /**
   * @param {!proto.pb.GetGuideRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.Guide.deserializeBinary
);


/**
 * @param {!proto.pb.GetGuideRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.Guide)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.Guide>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.GuideServiceClient.prototype.get =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.GuideService/Get',
      request,
      metadata || {},
      methodDescriptor_GuideService_Get,
      callback);
};


/**
 * @param {!proto.pb.GetGuideRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.Guide>}
 *     Promise that resolves to the response
 */
proto.pb.GuideServicePromiseClient.prototype.get =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.GuideService/Get',
      request,
      metadata || {},
      methodDescriptor_GuideService_Get);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.UpdateGuideRequest,
 *   !proto.pb.Guide>}
 */
const methodDescriptor_GuideService_Update = new grpc.web.MethodDescriptor(
  '/pb.GuideService/Update',
  grpc.web.MethodType.UNARY,
  proto.pb.UpdateGuideRequest,
  proto.pb.Guide,
  /**
   * @param {!proto.pb.UpdateGuideRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.Guide.deserializeBinary
);


/**
 * @param {!proto.pb.UpdateGuideRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.Guide)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.Guide>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.GuideServiceClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.GuideService/Update',
      request,
      metadata || {},
      methodDescriptor_GuideService_Update,
      callback);
};


/**
 * @param {!proto.pb.UpdateGuideRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.Guide>}
 *     Promise that resolves to the response
 */
proto.pb.GuideServicePromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.GuideService/Update',
      request,
      metadata || {},
      methodDescriptor_GuideService_Update);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.DeleteGuideRequest,
 *   !proto.pb.Empty>}
 */
const methodDescriptor_GuideService_Delete = new grpc.web.MethodDescriptor(
  '/pb.GuideService/Delete',
  grpc.web.MethodType.UNARY,
  proto.pb.DeleteGuideRequest,
  empty_pb.Empty,
  /**
   * @param {!proto.pb.DeleteGuideRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.pb.DeleteGuideRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.GuideServiceClient.prototype.delete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.GuideService/Delete',
      request,
      metadata || {},
      methodDescriptor_GuideService_Delete,
      callback);
};


/**
 * @param {!proto.pb.DeleteGuideRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.Empty>}
 *     Promise that resolves to the response
 */
proto.pb.GuideServicePromiseClient.prototype.delete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.GuideService/Delete',
      request,
      metadata || {},
      methodDescriptor_GuideService_Delete);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.ListGuideRequest,
 *   !proto.pb.ListGuideResponse>}
 */
const methodDescriptor_GuideService_List = new grpc.web.MethodDescriptor(
  '/pb.GuideService/List',
  grpc.web.MethodType.UNARY,
  proto.pb.ListGuideRequest,
  proto.pb.ListGuideResponse,
  /**
   * @param {!proto.pb.ListGuideRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.ListGuideResponse.deserializeBinary
);


/**
 * @param {!proto.pb.ListGuideRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.ListGuideResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.ListGuideResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.GuideServiceClient.prototype.list =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.GuideService/List',
      request,
      metadata || {},
      methodDescriptor_GuideService_List,
      callback);
};


/**
 * @param {!proto.pb.ListGuideRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.ListGuideResponse>}
 *     Promise that resolves to the response
 */
proto.pb.GuideServicePromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.GuideService/List',
      request,
      metadata || {},
      methodDescriptor_GuideService_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.BatchCreateGuidesRequest,
 *   !proto.pb.BatchCreateGuidesResponse>}
 */
const methodDescriptor_GuideService_BatchCreate = new grpc.web.MethodDescriptor(
  '/pb.GuideService/BatchCreate',
  grpc.web.MethodType.UNARY,
  proto.pb.BatchCreateGuidesRequest,
  proto.pb.BatchCreateGuidesResponse,
  /**
   * @param {!proto.pb.BatchCreateGuidesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.BatchCreateGuidesResponse.deserializeBinary
);


/**
 * @param {!proto.pb.BatchCreateGuidesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.BatchCreateGuidesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.BatchCreateGuidesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.GuideServiceClient.prototype.batchCreate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.GuideService/BatchCreate',
      request,
      metadata || {},
      methodDescriptor_GuideService_BatchCreate,
      callback);
};


/**
 * @param {!proto.pb.BatchCreateGuidesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.BatchCreateGuidesResponse>}
 *     Promise that resolves to the response
 */
proto.pb.GuideServicePromiseClient.prototype.batchCreate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.GuideService/BatchCreate',
      request,
      metadata || {},
      methodDescriptor_GuideService_BatchCreate);
};


module.exports = proto.pb;

