/**
 * @fileoverview gRPC-Web generated client stub for pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.1
// source: question.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var empty_pb = require('./empty_pb.js')
const proto = {};
proto.pb = require('./question_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pb.QuestionServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pb.QuestionServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.CreateQuestionRequest,
 *   !proto.pb.Question>}
 */
const methodDescriptor_QuestionService_Create = new grpc.web.MethodDescriptor(
  '/pb.QuestionService/Create',
  grpc.web.MethodType.UNARY,
  proto.pb.CreateQuestionRequest,
  proto.pb.Question,
  /**
   * @param {!proto.pb.CreateQuestionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.Question.deserializeBinary
);


/**
 * @param {!proto.pb.CreateQuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.Question)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.Question>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.QuestionServiceClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.QuestionService/Create',
      request,
      metadata || {},
      methodDescriptor_QuestionService_Create,
      callback);
};


/**
 * @param {!proto.pb.CreateQuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.Question>}
 *     Promise that resolves to the response
 */
proto.pb.QuestionServicePromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.QuestionService/Create',
      request,
      metadata || {},
      methodDescriptor_QuestionService_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.GetQuestionRequest,
 *   !proto.pb.Question>}
 */
const methodDescriptor_QuestionService_Get = new grpc.web.MethodDescriptor(
  '/pb.QuestionService/Get',
  grpc.web.MethodType.UNARY,
  proto.pb.GetQuestionRequest,
  proto.pb.Question,
  /**
   * @param {!proto.pb.GetQuestionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.Question.deserializeBinary
);


/**
 * @param {!proto.pb.GetQuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.Question)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.Question>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.QuestionServiceClient.prototype.get =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.QuestionService/Get',
      request,
      metadata || {},
      methodDescriptor_QuestionService_Get,
      callback);
};


/**
 * @param {!proto.pb.GetQuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.Question>}
 *     Promise that resolves to the response
 */
proto.pb.QuestionServicePromiseClient.prototype.get =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.QuestionService/Get',
      request,
      metadata || {},
      methodDescriptor_QuestionService_Get);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.UpdateQuestionRequest,
 *   !proto.pb.Question>}
 */
const methodDescriptor_QuestionService_Update = new grpc.web.MethodDescriptor(
  '/pb.QuestionService/Update',
  grpc.web.MethodType.UNARY,
  proto.pb.UpdateQuestionRequest,
  proto.pb.Question,
  /**
   * @param {!proto.pb.UpdateQuestionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.Question.deserializeBinary
);


/**
 * @param {!proto.pb.UpdateQuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.Question)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.Question>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.QuestionServiceClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.QuestionService/Update',
      request,
      metadata || {},
      methodDescriptor_QuestionService_Update,
      callback);
};


/**
 * @param {!proto.pb.UpdateQuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.Question>}
 *     Promise that resolves to the response
 */
proto.pb.QuestionServicePromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.QuestionService/Update',
      request,
      metadata || {},
      methodDescriptor_QuestionService_Update);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.DeleteQuestionRequest,
 *   !proto.pb.Empty>}
 */
const methodDescriptor_QuestionService_Delete = new grpc.web.MethodDescriptor(
  '/pb.QuestionService/Delete',
  grpc.web.MethodType.UNARY,
  proto.pb.DeleteQuestionRequest,
  empty_pb.Empty,
  /**
   * @param {!proto.pb.DeleteQuestionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.pb.DeleteQuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.QuestionServiceClient.prototype.delete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.QuestionService/Delete',
      request,
      metadata || {},
      methodDescriptor_QuestionService_Delete,
      callback);
};


/**
 * @param {!proto.pb.DeleteQuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.Empty>}
 *     Promise that resolves to the response
 */
proto.pb.QuestionServicePromiseClient.prototype.delete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.QuestionService/Delete',
      request,
      metadata || {},
      methodDescriptor_QuestionService_Delete);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.ListQuestionRequest,
 *   !proto.pb.ListQuestionResponse>}
 */
const methodDescriptor_QuestionService_List = new grpc.web.MethodDescriptor(
  '/pb.QuestionService/List',
  grpc.web.MethodType.UNARY,
  proto.pb.ListQuestionRequest,
  proto.pb.ListQuestionResponse,
  /**
   * @param {!proto.pb.ListQuestionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.ListQuestionResponse.deserializeBinary
);


/**
 * @param {!proto.pb.ListQuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.ListQuestionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.ListQuestionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.QuestionServiceClient.prototype.list =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.QuestionService/List',
      request,
      metadata || {},
      methodDescriptor_QuestionService_List,
      callback);
};


/**
 * @param {!proto.pb.ListQuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.ListQuestionResponse>}
 *     Promise that resolves to the response
 */
proto.pb.QuestionServicePromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.QuestionService/List',
      request,
      metadata || {},
      methodDescriptor_QuestionService_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pb.BatchCreateQuestionsRequest,
 *   !proto.pb.BatchCreateQuestionsResponse>}
 */
const methodDescriptor_QuestionService_BatchCreate = new grpc.web.MethodDescriptor(
  '/pb.QuestionService/BatchCreate',
  grpc.web.MethodType.UNARY,
  proto.pb.BatchCreateQuestionsRequest,
  proto.pb.BatchCreateQuestionsResponse,
  /**
   * @param {!proto.pb.BatchCreateQuestionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pb.BatchCreateQuestionsResponse.deserializeBinary
);


/**
 * @param {!proto.pb.BatchCreateQuestionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pb.BatchCreateQuestionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pb.BatchCreateQuestionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pb.QuestionServiceClient.prototype.batchCreate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pb.QuestionService/BatchCreate',
      request,
      metadata || {},
      methodDescriptor_QuestionService_BatchCreate,
      callback);
};


/**
 * @param {!proto.pb.BatchCreateQuestionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pb.BatchCreateQuestionsResponse>}
 *     Promise that resolves to the response
 */
proto.pb.QuestionServicePromiseClient.prototype.batchCreate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pb.QuestionService/BatchCreate',
      request,
      metadata || {},
      methodDescriptor_QuestionService_BatchCreate);
};


module.exports = proto.pb;

